services:
  - name: ai-study-sync-backend
    type: web
    instance:
      type: free
    ports:
      - port: 3000
        protocol: http
    routes:
      - path: /
        port: 3000
    env:
      - NODE_ENV=production
      - PORT=3000
    build:
      type: buildpack
    run:
      command: cd backend && npm start
    regions:
      - was
    scaling:
      min: 1
      max: 1
    healthchecks:
      - http:
          path: /api/health
          port: 3000
        grace_period: 40
        interval: 30
        restart_limit: 3
        timeout: 5

